### ISSUE TITLE
void QTinyAes::restorePlainText(QByteArray &data) broken?

### ISSUE THREAD

**Issue by luntik2012** [Skycoder42/QTinyAes#3]
data	"2019-01-02      "	QByteArray &
				'2' 	50    	0x32	char
				'0' 	48    	0x30	char
				'1' 	49    	0x31	char
				'9' 	57    	0x39	char
				'-' 	45    	0x2d	char
				'0' 	48    	0x30	char
				'1' 	49    	0x31	char
				'-' 	45    	0x2d	char
				'0' 	48    	0x30	char
				'2' 	50    	0x32	char
				' ' 	32    	0x20	char
				' ' 	32    	0x20	char
				' ' 	32    	0x20	char
				' ' 	32    	0x20	char
				' ' 	32    	0x20	char
				' ' 	32    	0x20	char

```cpp
auto padding = data.at(data.size() - 1);
data.chop((int)padding);
```

is it necessary set last byte to padding?

padding is 0d32/0x20 here, array is chopped by 32, so result is empty

**Comment by Skycoder42** [comment]
It's not the padding that is broken, it is your data. If you pass `"2019-01-02 "` (with one space, i.e. 0x20 at the end) to `QTinyAes::preparePlainText`, it will apply the padding and correctly set the data to `"2019-01-02 \x05\x05\x05\x05\x05"` - which is unpadded correctly if passed to `QTinyAes::restorePlainText`. (passing it without a space would result in `"2019-01-02\x06\x06\x06\x06\x06\x06"`)

I don't know where your data comes from, but it is not correctly padded (See [PKCS#7](https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS#5_and_PKCS#7))

**Comment by luntik2012** [comment]
https://github.com/jangko/nimAES

there is no padding in this lib O_o

**Comment by Skycoder42** [comment]
If you want to use this library without a padding, you can use the `encryptRaw` and `decryptRaw` methods. The still require data with a length of `<n> * blocksize`, but at least for the CTR-Mode, you can simply drop the additional bytes after encryption
